# This is a basic workflow to help you get started with Actions

name: Perf Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Linux-PSGetv2:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path |  Remove-Item -Recurse -Force -Verbose
      - name: install
        run: |
          Install-Module Az -Verbose -Force
  Linux-PSGetv3:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose

      - name: install
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose

          Install-Module -Name Microsoft.PowerShell.PSResourceGet -AllowPrerelease -Force
          Install-PSResource Az -Verbose -TrustRepository
  Linux-moduleFast:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose
      - name: install
        run: |
          iwr bit.ly/modulefast | iex
          Install-ModuleFast Az -Verbose

  Win-PSGetv2:
    runs-on: windows-latest
    steps:
      - name: cleanup
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose
      - name: install
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose

          Install-Module Az -Verbose -Force
  Win-PSGetv3:
    runs-on: windows-latest
    steps:
      - name: cleanup
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose
      - name: install
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose

          Install-Module -Name Microsoft.PowerShell.PSResourceGet -AllowPrerelease -Force
          Install-PSResource Az -Verbose -TrustRepository
  Win-moduleFast:
    runs-on: windows-latest
    steps:
      - name: cleanup
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose
      - name: install
        run: |
          get-module -ListAvailable az* |% modulebase | Split-Path | Remove-Item -Recurse -Force -Verbose

          iwr bit.ly/modulefast | iex
          Install-ModuleFast Az -Verbose

  Linux-PSGetv2-update:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: |
          Update-Module Az -Verbose -Force
  Linux-PSGetv3-update:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          Install-Module -Name Microsoft.PowerShell.PSResourceGet -AllowPrerelease -Force
          Update-PSResource Az -Verbose -TrustRepository
  Linux-moduleFast-update:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: |
          iwr bit.ly/modulefast | iex
          Install-ModuleFast Az -Update -Verbose
